# Generated by Django 2.0.2 on 2018-06-04 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermsgs', to='usermsg.MsgBox'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
