# Generated by Django 2.0.2 on 2018-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermsg', '0002_auto_20180604_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
